version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - wordpress_db_data:/var/lib/mysql
    networks:
      vlan105_macvlan:
        ipv4_address: 5.5.5.4

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    depends_on:
      - db
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: 5.5.5.4:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    networks:
      vlan105_macvlan:
        ipv4_address: 5.5.5.5
