version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      vlan105_macvlan:
        ipv4_address: 5.5.5.4

  wordpress:
    image: wordpress:latest
    container_name: wordpress_site
    depends_on:
      - db
    networks:
      vlan105_macvlan:
        ipv4_address: 5.5.5.5
    restart: always
    environment:
      WORDPRESS_DB_HOST: 5.5.5.4:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data:

networks:
  vlan105_macvlan:
    external: true
