etwork:
  version: 2
  renderer: networkd

  ethernets:
    ens34:
      dhcp4: true
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
    ens37:
      dhcp4: no

  vlans:
    ens37.105:
      id: 105
      link: ens37
      addresses: [5.5.5.3/26]
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 5.5.5.1
