version: "3.7"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    networks:
      macnet:
        ipv4_address: 10.0.10.12
    volumes:
      - /home/zakaria/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  macnet:
    external: true
